name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'install deps'
      run: "sudo apt install -y libfreetype6-dev gsfonts libmagickwand-dev imagemagick"
    - name: 'install deps2'
      run: "which convert"
    - uses: actions/checkout@v4
    - name: 'install deps3'
      run: "sudo mv /usr/bin/convert /usr/bin/converto"
    - name: 'install deps4'
      run: "sudo apt install inkscape"
    
    - name: autogen.sh
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: 'install deps2'
      run: "which convert"
    
